CREATE TABLE cc_user_account (id varchar(255) primary key, display_name varchar(255), password_hash varchar(255), active boolean not null, version bigint not null);
CREATE TABLE cc_user_group (id varchar(255) primary key, name varchar(255), active boolean not null, version bigint not null);
CREATE TABLE cc_membership (id varchar(255) primary key, user_id varchar(255) not null references cc_user_account(id), group_id varchar(255) not null references cc_user_group(id), version bigint not null, constraint cc_uq_membership unique(user_id,group_id));
CREATE TABLE cc_permission_grant (id varchar(255) primary key, group_id varchar(255) not null references cc_user_group(id), feature varchar(255) not null, action varchar(255) not null, scope varchar(255) not null, version bigint not null, hidden_fields varchar(255), constraint cc_uq_grant unique(group_id,feature,action,scope));
CREATE TABLE cc_security_change (id varchar(255) primary key, kind varchar(255), payload varchar(16000), maker varchar(255), checker varchar(255), reason varchar(255), decision_reason varchar(255), status varchar(255), submitted_at timestamp(6) with time zone, decided_at timestamp(6) with time zone, version bigint not null);
CREATE TABLE cc_setup_record (id varchar(255) primary key, feature varchar(255) not null, scope varchar(255) not null, business_key varchar(255) not null, data varchar(16000), status varchar(255), updated_at timestamp(6) with time zone, version bigint not null, constraint cc_uq_record unique(feature,scope,business_key));
CREATE TABLE cc_change_request (id varchar(255) primary key, feature varchar(255), scope varchar(255), business_key varchar(255), record_id varchar(255), pending_key varchar(255) unique, action varchar(255), status varchar(255), baseline_version bigint not null, before_data varchar(16000), proposed_data varchar(16000), maker varchar(255), checker varchar(255), reason varchar(1000), decision_reason varchar(1000), submitted_at timestamp(6) with time zone, decided_at timestamp(6) with time zone, version bigint not null);
CREATE TABLE cc_audit_event (id varchar(255) primary key, category varchar(255), feature varchar(255), scope varchar(255), record_id varchar(255), reference_id varchar(255), action varchar(255), status varchar(255), actor varchar(255), maker varchar(255), checker varchar(255), reason varchar(1000), source varchar(255), trace_id varchar(255), occurred_at timestamp(6) with time zone not null, before_values varchar(24000), after_values varchar(24000));
CREATE TABLE cc_report_job (id varchar(255) primary key, owner varchar(255), audience_group varchar(255), trigger_type varchar(255), occurrence_key varchar(255) unique, format varchar(255), status varchar(255), criteria varchar(8000), allowed_pairs varchar(16000), field_footprint varchar(16000), trace_id varchar(255), failure_code varchar(255), requested_at timestamp(6) with time zone, ready_at timestamp(6) with time zone, expires_at timestamp(6) with time zone, row_count bigint not null, version bigint not null);
CREATE TABLE cc_report_schedule (id varchar(255) primary key, owner varchar(255), audience_group varchar(255), name varchar(255), category varchar(255), feature varchar(255), scope varchar(255), format varchar(255), enabled boolean not null, interval_days integer not null, next_run_at timestamp(6) with time zone, last_failure varchar(255), version bigint not null);
CREATE TABLE cc_retention_run (id varchar(255) primary key, started_at timestamp with time zone not null, cutoff timestamp with time zone not null, eligible_count bigint not null, deleted_count bigint not null, dry_run boolean not null, trace_id varchar(255));
CREATE INDEX cc_idx_audit_scope_time ON cc_audit_event(scope, feature, occurred_at, id);
CREATE INDEX cc_idx_audit_reference ON cc_audit_event(reference_id);
CREATE INDEX cc_idx_audit_actor ON cc_audit_event(actor, occurred_at);
CREATE INDEX cc_idx_audit_expiry ON cc_audit_event(occurred_at);
CREATE INDEX cc_idx_report_queue ON cc_report_job(status, requested_at);
CREATE INDEX cc_idx_change_pending ON cc_change_request(status, scope);
CREATE USER IF NOT EXISTS cc_app PASSWORD '${appPassword}';
CREATE USER IF NOT EXISTS cc_retention PASSWORD '${retentionPassword}';
GRANT SELECT, INSERT, UPDATE, DELETE ON cc_user_account TO cc_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON cc_user_group TO cc_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON cc_membership TO cc_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON cc_permission_grant TO cc_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON cc_security_change TO cc_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON cc_setup_record TO cc_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON cc_change_request TO cc_app;
GRANT SELECT, INSERT ON cc_audit_event TO cc_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON cc_report_job TO cc_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON cc_report_schedule TO cc_app;
GRANT SELECT ON cc_retention_run TO cc_app;
GRANT SELECT, DELETE ON cc_audit_event TO cc_retention;
GRANT SELECT, INSERT ON cc_retention_run TO cc_retention;

CREATE TABLE cc_report_artifact(id varchar(255) primary key references cc_report_job(id), content blob);
GRANT SELECT, INSERT, DELETE ON cc_report_artifact TO cc_app;
